### ISSUE TITLE
S07 - Incremental 3D Line Segment Extraction from Semi-dense SLAM

### ISSUE THREAD

**Issue by kerautret** [RLPR/LabelReviews#1]
# General info
- [x] Conference: ICPR 2018
- [x] Source paper:  [paper S07](https://github.com/kerautret/PrivatePDFforRLPR/blob/master/s07.pdf)
- [x] Papers title: Incremental 3D Line Segment Extraction from Semi-dense SLAM
- [x] GitHub repo: https://github.com/shidahe/semidense-lines
- [x] Submission date: 13/07/2018
- [x] Platform: Ubuntu 14.04
- [x] Language: C++
- [x] Results to be reproduced: Fig. 4, Fig 5, Fig 6, Table 1, Table 2,  
- [x] Reproduction main step instructions:
```
      Installations steps given here https://github.com/shidahe/semidense-lines/blob/master/README.md
      Reproductions of figures:
       Fig 4: ... 
       Fig 5: ... 
       Fig 6: ... 
       Table 1:  ... 
       Table 2: ....
```

# Reviewer feedback
 - [ ] Tested platform: 
 - [ ]  Result reproduced: 
 - [ ]  Reviewer comment:

## Details Results
- Execution without errors:
    - [ ] without changes
    - [ ] with small changes
    - [ ] with a lot of changes
- Results are obtained:
    - [ ] always
    - [ ] sometimes
    - [ ] never
- Results correspond to the paper's figures/tables:
    - [ ] exactly
    - [ ] with negligible differences
    - [ ] with differences
    - [ ] with a lot of differences

**Comment by kerautret** [comment]
@shidahe Could you please add the command description to reproduce the results ? (to complete the review form and simplifiante the reviewing work)

 - [ ] Platform:
 - [ ] Language:
 - [ ] Results to be reproduced: (indicates reference to figure/tab)
 - [ ]  Reproduction main step instructions:
- [ ] Reproduction main step instructions:
       `Give the main steps to reproduce the figure/tab`

**Comment by kerautret** [comment]
@shidahe perfect thanks!

**Comment by kerautret** [comment]
@shidahe I succès to compile the code from your script, however I have some issue to reproduce Fig 4. Probably due to 32 bit version ?

**Comment by shidahe** [comment]
@kerautret Sorry about that, but I have only tested it on 64bit machines. I think it is highly possible that the 32bit version is the reason.

**Comment by kerautret** [comment]
Ok I download a new image of 64 bit one and test I test it again ;)

**Comment by kerautret** [comment]
@shidahe I confirm just had the first result of first line of figure 4! 🌟

**Comment by kerautret** [comment]
All was fine from previous test I miss to update the tag 😱
