### ISSUE TITLE
S19 - A Heuristic-Based Decision Tree for Connected Components Labeling of 3D Volumes

### ISSUE THREAD

**Issue by prittt** [RLPR/LabelReviews#19]
# General info
- [x] Conference: [ICPR2020](https://www.micc.unifi.it/icpr2020/)
- [x] Submission date: July 14, 2020 
- [x] Papers title: A Heuristic-Based Decision Tree for Connected Components Labeling of 3D Volumes 
- [x] Source paper: [A Heuristic-Based Decision Tree for Connected Components Labeling of 3D Volumes ](https://prittt.github.io/pub_files/2021icpr_labeling.pdf)
- [x] GitHub repo: [YACCLAB](https://github.com/prittt/YACCLAB)
- [x] Platform: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz with Windows 10.0.17134 (64 bit) OS and MSVC 19.15.26730 compiler.
- [x] Language: <em>C++</em>
- [x] Results that can be reproduced: TABLE II, TABLE III, Fig. 6. Experimental results reported in TABLE II and Fig. 6 can be affected by the environment employed for testing the algorithms. In particular, cache size and RAM speed can change absolute results while preserving relative performance. Operative System and compiler are likely to heavily influence the outcome. Numbers reported in TABLE III, instead, should be totally independent from the chosen environment.
- [x] Reproduction main step instructions: [Specific instructions here](https://github.com/prittt/YACCLAB/tree/master/doc/EPDT)

# Reviewer feedback
 - [ ] Tested platform: 
 - [ ]  Result reproduced: 
 - [ ]  Reviewer comment:

## Details Results
- Execution without errors:
    - [ ] without changes
    - [ ] with small changes
    - [ ] with a lot of changes
- Results are obtained:
    - [ ] always
    - [ ] sometimes
    - [ ] never
- Results correspond to the paper's figures/tables:
    - [ ] exactly
    - [ ] with negligible differences
    - [ ] with differences
    - [ ] with a lot of differences

**Comment by paulviville** [comment]
Hello,
I'm running into a bit of trouble trying to build the project.
I am working on the following:
- Dell Precision 5540 laptop (GPU Quadro T1000), Xubuntu 20.04, using GCC

I've followed your instructions to configure CMake, but labeling3D_EDPT22.c and 26 will not build. 19 builds fine, but the other two just seem to get stuck, nothing happens and there are no errors. I tried over from scratch and the same thing happens. I've never encountered such a problem before, Might you know what is causing it?

**Comment by stal12** [comment]
The problem could be related to the large code size of EPDT algorithms.
Our Linux system is a desktop computer with:
- Intel(R) Core(TM) i7-4790 CPU @ 3.60 GH
- 16 GB RAM
- Ubuntu 16.04.7 LTS
- gcc 9.3.0

EPDT_22c is compiled in 10 minutes, while EPDT_26c needs 1 hour and a half; you can try to wait some more time.

**Comment by prittt** [comment]
@paulviville which version of GCC are you using? 

If you don't manage to build the two algorithms in a reasonable timeframe, we can provide you with an object file for both EPDT22c and EPDT26c or a docker image with the same environmental setup you mentioned above and the whole framework already built.

**Comment by paulviville** [comment]
I left for several hours, it seems to be done.
Sorry for the worry

**Comment by prittt** [comment]
Great! Thank you for your effort.

**Comment by paulviville** [comment]
I checked up all the results.
Everything is perfectly in order.
Interestingly, my results for 26c for table 2 are all lower. In your table you have a factor of ~1.7 between results oif 22c and 26c, in my tests it's closer to 1.1.
My alloc & dealloc times for figure 6 graphs are also a fraction of yours, so I assume my work computer has better hardware than what you used.
Could that be the cause of such a huge change for the results of table 2?

**Comment by stal12** [comment]
It is possibile that your hardware is better than what we used, but we have to consider another key element: the operating system.
Results in the paper have been obtained on Windows, which has a worse performing memory management system ([Towards Reliable Experiments on the Performance of Connected Components Labeling Algorithms, Journal of Real-Time Image Processing](https://prittt.github.io/pub_files/2018jrtip.pdf)).

**Comment by paulviville** [comment]
Hello again,
The instructions you give here on how to reproduce the tables of your article are very straight forward and useful.
Your git contains what seems to be a fairly comprehensive manual.
For the purpose of ICPR, do you think you could add the instructions here somewhere on your git? A small Readme explicitly on the topic of reproducing the results of your article, or a small section in your main description?

Best regards

**Comment by prittt** [comment]
Yes, of course. I've just created a separated README inside the doc folder of the YACCLAB project: you can find it [here](https://github.com/prittt/YACCLAB/tree/master/doc/EPDT). A link pointing to that page is available also in the main YACCLAB README.
