### ISSUE TITLE
S20 - Planar 3D Transfer Learning for End to End Unimodal MRI Unbalanced Data Segmentation

### ISSUE THREAD

**Issue by mrkolarik** [RLPR/LabelReviews#20]
# General info
- [x] Conference: ICPR 2020
- [x] Submission date: November 24 2020
- [x] Papers title: On the Implementation of Planar 3D Transfer Learning for End to End Unimodal MRI Unbalanced Data Segmentation
- [x] Source paper: [Planar 3D Transfer Learning for End to End Unimodal MRI Unbalanced Data Segmentation](https://arxiv.org/abs/2011.11557)
- [x] GitHub repo: https://github.com/mrkolarik/transfer2d3d
- [x] Platform: Ubuntu
- [x] Language: Python 3.7
- [x] Results that can be reproduced: Fig. 5 in the original paper - our prediction = pred_682.png in the ./preds/planar_cross_1 folder after prediction. Table 2 in the original paper is a result of cross-validation, we provide weights to reproduce first round of cross-validation, which can be found in the accompanying paper in Table 2.
- [x] Reproduction main step instructions: [Complete instruction in the Github repository](https://github.com/mrkolarik/transfer2d3d/blob/master/README.md)

# Reviewer feedback
 - [ ] Tested platform: 
 - [ ]  Result reproduced: 
 - [ ]  Reviewer comment:

## Details Results
- Execution without errors:
    - [ ] without changes
    - [ ] with small changes
    - [ ] with a lot of changes
- Results are obtained:
    - [ ] always
    - [ ] sometimes
    - [ ] never
- Results correspond to the paper's figures/tables:
    - [ ] exactly
    - [ ] with negligible differences
    - [ ] with differences
    - [ ] with a lot of differences

**Comment by elnrdfrs** [comment]
Hello @mrkolarik, I am the reviewer assigned to your paper and implementation for the reproductible label. 
I did manage to obtain the results that were reported on Figure 5 and Table 2 of your paper. However, I do have some comments on the instructions provided in the GitHub repository:
- The command you provide for creating the conda environment should come before the instruction to run the nifti_to_png.py script.
- Although the opencv package is present in the environment.txt package plan, I still encounter the 'No module named cv2' problem when I launch evaluate_predictions.py. When I tried installing opencv with conda, I encountered the following message: 
```
conda install -c conda-forge opencv Collecting package metadata (current_repodata.json): done
Solving environment: | 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:
...
```
-  I got around the problem (without actually solving it) by installing opencv-python with pip3 outside the planar3d environment.
- Afterwards, evaluate_predictions.py yielded the expected output.

**Comment by mrkolarik** [comment]
Hello,

thank you for your feedback. As I have already had many troubles with Conda installation before, I decided to add your workaround solution to the open-cv installation problem to our readme.

With kind regards,

Martin Kolarik

**Comment by elnrdfrs** [comment]
# Reviewer feedback
 - [x] Tested platform: Ubuntu, Python 3.7
 - [x]  Result reproduced:  Fig. 5 in the original paper - our prediction = pred_682.png in the ./preds/planar_cross_1 folder after prediction. Table 2 in the original paper is a result of cross-validation, we provide weights to reproduce first round of cross-validation, which can be found in the accompanying paper in Table 2.
 - [x]  Reviewer comment: Small issues during the installation of the modules in the provided environment.txt, but a workaround solution was found and added to the documentation. The results were successfully reproduced.

## Details Results
- Execution without errors:
    - [x] without changes
    - [ ] with small changes
    - [ ] with a lot of changes
- Results are obtained:
    - [x] always
    - [ ] sometimes
    - [ ] never
- Results correspond to the paper's figures/tables:
    - [x] exactly
    - [ ] with negligible differences
    - [ ] with differences
    - [ ] with a lot of differences
